artifacts_root: artifacts

data_ingestion:
  {"root_dir":"artifacts/data_ingestion",
  "source_url":"https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=drive_link",
  "local_data_file":"artifacts/data_ingestion/data.zip",
  "unzip_data_dir":"artifacts/data_ingestion"}

prepare_model:
  {"root_dir":"artifacts/prepare_model",
  "base_model_path":"artifacts/prepare_model/base_model.h5",
  "updated_model_path":"artifacts/prepare_model/updated_base_model.h5"
  }

model_training:
  {"root_dir":"artifacts/model_training",
  "trained_model_path":"artifacts/model_training/trained_model.h5"
  }

model_evaluation:
  {
  "model_path":"artifacts/model_training/trained_model.h5",
  "training_data":"artifacts/data_ingestion/kidney-ct-scan-image",
  "mlflow_uri":"https://dagshub.com/nagarajan.bala/image_classification.mlflow"
  }
